/**
 * Injects performance resource hints into <head> as early as possible.
 *
 * Why runtime instead of index.html: this project's HTML entry is generated by
 * the Make/Figma toolchain and is not editable, so we add the hints from the app
 * entry. This still runs before React renders and before any image/font request,
 * so the browser can warm up TCP/TLS to our CDNs ahead of time.
 */

const SUPABASE_ORIGIN = 'https://njgdeljfvprnkckgyiuy.supabase.co';
const FIRST_HERO_IMAGE =
  'https://njgdeljfvprnkckgyiuy.supabase.co/storage/v1/object/public/COFKANSELECTRICALS/Hero/477a75df-5b81-4970-91e2-69759880c272.jpeg';

const PRECONNECT: { href: string; crossorigin?: boolean }[] = [
  { href: SUPABASE_ORIGIN, crossorigin: true },
  { href: 'https://fonts.googleapis.com' },
  { href: 'https://fonts.gstatic.com', crossorigin: true },
  { href: 'https://images.unsplash.com', crossorigin: true },
];

const DNS_PREFETCH = [SUPABASE_ORIGIN, 'https://images.unsplash.com'];

function add(rel: string, href: string, opts: { as?: string; crossorigin?: boolean; fetchpriority?: string } = {}) {
  // Avoid duplicates if hot-reloaded.
  if (document.head.querySelector(`link[rel="${rel}"][href="${href}"]`)) return;
  const link = document.createElement('link');
  link.rel = rel;
  link.href = href;
  if (opts.as) link.as = opts.as;
  if (opts.crossorigin) link.crossOrigin = 'anonymous';
  if (opts.fetchpriority) link.setAttribute('fetchpriority', opts.fetchpriority);
  document.head.appendChild(link);
}

export function installResourceHints(): void {
  if (typeof document === 'undefined') return;
  for (const p of PRECONNECT) add('preconnect', p.href, { crossorigin: p.crossorigin });
  for (const href of DNS_PREFETCH) add('dns-prefetch', href);
  // Preload the LCP hero image so it starts downloading immediately.
  add('preload', FIRST_HERO_IMAGE, { as: 'image', fetchpriority: 'high' });
}
