/**
 * Injects performance resource hints into <head> as early as possible.
 *
 * Why runtime instead of index.html: this project's HTML entry is generated by
 * the Make/Figma toolchain and is not editable, so we add the hints from the app
 * entry. This still runs before React renders and before any image/font request,
 * so the browser can warm up TCP/TLS to our CDNs ahead of time.
 */

const PRECONNECT: { href: string; crossorigin?: boolean }[] = [
  { href: 'https://images.unsplash.com', crossorigin: true },
  { href: 'https://fonts.googleapis.com' },
  { href: 'https://fonts.gstatic.com', crossorigin: true },
];

const DNS_PREFETCH = ['https://images.unsplash.com'];

function add(rel: string, href: string, opts: { crossorigin?: boolean } = {}) {
  if (document.head.querySelector(`link[rel="${rel}"][href="${href}"]`)) return;
  const link = document.createElement('link');
  link.rel = rel;
  link.href = href;
  if (opts.crossorigin) link.crossOrigin = 'anonymous';
  document.head.appendChild(link);
}

export function installResourceHints(): void {
  if (typeof document === 'undefined') return;
  for (const p of PRECONNECT) add('preconnect', p.href, { crossorigin: p.crossorigin });
  for (const href of DNS_PREFETCH) add('dns-prefetch', href);
}
