// AUTO-GENERATED from src/imports/cofkans_electricals_urls.csv
// Do not edit by hand. Run `npm run build:image-map` to regenerate.

export const PRODUCT_IMAGE_URLS: Record<string, string> = {
  "100w floodlight gn type high matrix": "/product-images/100W FLOODLIGHT GN TYPE (High Matrix).png",
  "100w floodlight gn type slim smd": "/product-images/100W FLOODLIGHT GN TYPE (Slim SMD).png",
  "100w floodlight gn type": "/product-images/100W FLOODLIGHT GN TYPE.png",
  "100w street light grid pattern": "/product-images/100W STREET LIGHT (GRID PATTERN).png",
  "100w street light pole mount": "/product-images/100W STREET LIGHT (POLE MOUNT).png",
  "150w led floodlight": "/product-images/150W LED FLOODLIGHT.png",
  "150w street light grid pattern": "/product-images/150W STREET LIGHT (GRID PATTERN).png",
  "150w street light pole mount": "/product-images/150W STREET LIGHT (POLE MOUNT).png",
  "150w street light": "/product-images/150W STREET LIGHT.png",
  "200w led floodlight": "/product-images/200W LED FLOODLIGHT.png",
  "200w street light pole mount": "/product-images/200W STREET LIGHT (POLE MOUNT).png",
  "200w street light": "/product-images/200W STREET LIGHT.png",
  "20w floodlight 3000 500k 10w variant": "/product-images/20W FLOODLIGHT 3000+500K (10W Variant).png",
  "250w street light pole mount": "/product-images/250W STREET LIGHT (POLE MOUNT).png",
  "3 gang extension plug base pack": "/product-images/3-GANG EXTENSION PLUG BASE PACK.png",
  "3 gang extension socket type b": "/product-images/3-GANG EXTENSION SOCKET TYPE B.png",
  "3 in 1 cylindrical glass shade pendant cluster": "/product-images/3-IN-1 CYLINDRICAL GLASS SHADE PENDANT CLUSTER.png",
  "3 light track bar spotlight fixture": "/product-images/3-LIGHT TRACK BAR SPOTLIGHT FIXTURE.png",
  "3 light white track glow bar system": "/product-images/3-LIGHT WHITE TRACK GLOW BAR SYSTEM.png",
  "3 pole circuit breaker 100a": "/product-images/3-POLE CIRCUIT BREAKER 100A.png",
  "3 tier refined crystal chandelier loop": "/product-images/3-TIER REFINED CRYSTAL CHANDELIER LOOP.png",
  "3 tier ventilated louver bulkhead fitting": "/product-images/3-TIER VENTILATED LOUVER BULKHEAD FITTING.png",
  "3 way conduit round box type a": "/product-images/3-WAY CONDUIT ROUND BOX TYPE A.png",
  "300w led floodlight 400w variant": "/product-images/300W LED FLOODLIGHT (400W Variant).png",
  "300w led floodlight 500w variant": "/product-images/300W LED FLOODLIGHT (500W Variant).png",
  "300w led floodlight bracket mount": "/product-images/300W LED FLOODLIGHT (Bracket Mount).png",
  "300w led floodlight warm white light test": "/product-images/300W LED FLOODLIGHT (Warm White Light Test).png",
  "300w led floodlight": "/product-images/300W LED FLOODLIGHT.png",
  "300w street light pole mount": "/product-images/300W STREET LIGHT (POLE MOUNT).png",
  "300w street light": "/product-images/300W STREET LIGHT.png",
  "4 arm hollow glass shade chandelier": "/product-images/4-ARM HOLLOW GLASS SHADE CHANDELIER.png",
  "4 way 5 way extension multi socket": "/product-images/4-WAY   5-WAY EXTENSION MULTI-SOCKET.png",
  "41406m 13a 2 gang switched multi function socket": "/product-images/41406M - 13A 2 GANG SWITCHED MULTI FUNCTION SOCKET.png",
  "41689 13a 2 gang multi socket with neon usb gold vc400": "/product-images/41689 - 13A 2 GANG MULTI SOCKET WITH NEON USB GOLD (VC400).png",
  "50w floodlight gn type slim smd": "/product-images/50W FLOODLIGHT GN TYPE (Slim SMD).png",
  "50w floodlight gn type": "/product-images/50W FLOODLIGHT GN TYPE.jpg",
  "50w led floodlight wt type angled": "/product-images/50W LED FLOODLIGHT WT-TYPE (Angled).webp",
  "50w led floodlight wt type": "/product-images/50W LED FLOODLIGHT WT-TYPE.png",
  "50w street light pole mount copy 1": "/product-images/50W STREET LIGHT (POLE MOUNT) (copy 1).png",
  "50w street light pole mount": "/product-images/50W STREET LIGHT (POLE MOUNT).png",
  "50w street light": "/product-images/50W STREET LIGHT.png",
  "71301w 1 gang 1 way switch wide dolly": "/product-images/71301W 1 GANG 1 WAY SWITCH WIDE DOLLY.png",
  "71304w 2 gang 2 way switch wide dolly": "/product-images/71304W 2 GANG 2 WAY SWITCH WIDE DOLLY.png",
  "71304wch 2 gang 2 way switch wide dolly": "/product-images/71304WCH 2 GANG 2 WAY SWITCH WIDE DOLLY.png",
  "71306 3 gang 2 way switch": "/product-images/71306 3 GANG 2 WAY SWITCH.png",
  "71306ch 3 gang 2 way switch": "/product-images/71306CH 3 GANG 2 WAY SWITCH.png",
  "71324ac ch air condition switch a1105": "/product-images/71324AC CH AIR CONDITION SWITCH (A1105).png",
  "71364 4 gang 2 way switch": "/product-images/71364 4 GANG 2 WAY SWITCH.png",
  "71364w 4 gang 2 way switch wide dolly": "/product-images/71364W 4 GANG 2 WAY SWITCH WIDE DOLLY.png",
  "71405 ch 13a single socket gold rivet": "/product-images/71405 CH 13A SINGLE SOCKET (GOLD RIVET).png",
  "71432 tv socket": "/product-images/71432 TV SOCKET.png",
  "81406m 13a 2 gang switched multi function socket": "/product-images/81406M - 13A 2 GANG SWITCHED MULTI FUNCTION SOCKET.png",
  "81689q 13a 2 gang multi socket with neon usb vc300": "/product-images/81689Q - 13A 2 GANG MULTI SOCKET WITH NEON USB (VC300).png",
  "91302efq 1 gang 2 gang switch g1302efd": "/product-images/91302EFQ 1 GANG 2 GANG SWITCH (G1302EFD).png",
  "91408m 13a double multi socket": "/product-images/91408M 13A DOUBLE MULTI SOCKET.png",
  "91408mb 13a double multi socket usb": "/product-images/91408MB 13A DOUBLE MULTI SOCKET+USB.png",
  "91432 tv socket vc 202": "/product-images/91432 TV SOCKET (VC 202).png",
  "amber glass cylinder indoor sconce": "/product-images/AMBER GLASS CYLINDER INDOOR SCONCE.png",
  "amber globe garden bollard": "/product-images/AMBER GLOBE GARDEN BOLLARD.png",
  "arched window pillar gate light column": "/product-images/ARCHED WINDOW PILLAR GATE LIGHT COLUMN.png",
  "armoured power cable steel core coil": "/product-images/ARMOURED POWER CABLE STEEL CORE COIL.png",
  "arrowhead wedge surface wall pack": "/product-images/ARROWHEAD WEDGE SURFACE WALL PACK.png",
  "automatic control mains change over controller": "/product-images/AUTOMATIC CONTROL MAINS CHANGE-OVER CONTROLLER.png",
  "avr automatic voltage regulator dual pack": "/product-images/AVR AUTOMATIC VOLTAGE REGULATOR DUAL PACK.png",
  "b568 led wall lamp dy wl 50w 300k": "/product-images/B568 LED WALL LAMP  DY-WL 50W 300K.webp",
  "baroque half moon gold carved shield cove": "/product-images/BAROQUE HALF-MOON GOLD CARVED SHIELD COVE.png",
  "black pvc insulated conduit cable coil": "/product-images/BLACK PVC INSULATED CONDUIT CABLE COIL.png",
  "blue box eco led downlight fitting": "/product-images/BLUE BOX ECO LED DOWNLIGHT FITTING.png",
  "boho cage metallic drop cone trio": "/product-images/BOHO CAGE METALLIC DROP CONE TRIO.png",
  "bow tie sculptural backlight outdoor sconce copy 1": "/product-images/BOW-TIE SCULPTURAL BACKLIGHT OUTDOOR SCONCE (copy 1).png",
  "bow tie sculptural backlight outdoor sconce": "/product-images/BOW-TIE SCULPTURAL BACKLIGHT OUTDOOR SCONCE.png",
  "brass filigree four sided lawn lantern": "/product-images/BRASS FILIGREE FOUR-SIDED LAWN LANTERN.png",
  "brass filigree pillar base mount pack": "/product-images/BRASS FILIGREE PILLAR BASE MOUNT PACK.png",
  "brown porcelain shackle insulator copy 1": "/product-images/BROWN PORCELAIN SHACKLE INSULATOR (copy 1).png",
  "brown porcelain shackle insulator": "/product-images/BROWN PORCELAIN SHACKLE INSULATOR.png",
  "brushed chrome slit shield scoop wall cove": "/product-images/BRUSHED CHROME SLIT SHIELD SCOOP WALL COVE.png",
  "c301 1 gang 1 way switch": "/product-images/C301 1 GANG 1 WAY SWITCH.png",
  "c302 1 gang 2 way switch close up": "/product-images/C302 1 GANG 2 WAY SWITCH (CLOSE-UP).png",
  "c302 1 gang 2 way switch": "/product-images/C302 1 GANG 2 WAY SWITCH.png",
  "c324w ac air condition switch wide dolly vp 42": "/product-images/C324W(AC) AIR CONDITION SWITCH WIDE DOLLY (VP 42).png",
  "c324wh water heater switch gold frame": "/product-images/C324WH WATER HEATER SWITCH GOLD FRAME.png",
  "c324wh water heater switch": "/product-images/C324WH WATER HEATER SWITCH.png",
  "c331 cooker unit switch": "/product-images/C331 COOKER UNIT SWITCH.png",
  "c407m 13a single multi socket": "/product-images/C407M 13A SINGLE MULTI SOCKET.png",
  "c408m 13a double multi socket": "/product-images/C408M 13A DOUBLE MULTI SOCKET.png",
  "c408mb 13a double multi socket 2 usb": "/product-images/C408MB 13A DOUBLE MULTI SOCKET + 2 USB.png",
  "capsule oval horizontal slit decorative sconce": "/product-images/CAPSULE OVAL HORIZONTAL SLIT DECORATIVE SCONCE.png",
  "caret cage bunker light flush block": "/product-images/CARET CAGE BUNKER LIGHT FLUSH BLOCK.png",
  "cascading rain drop chandelier pack": "/product-images/CASCADING rain DROP CHANDELIER PACK.png",
  "central automatic voltage stabilizer 2000va": "/product-images/CENTRAL AUTOMATIC VOLTAGE STABILIZER 2000VA.png",
  "chrome ring inner crystal bright loops": "/product-images/CHROME RING INNER CRYSTAL BRIGHT LOOPS.png",
  "circular led ring crystal orbit layer": "/product-images/CIRCULAR LED RING CRYSTAL ORBIT LAYER.png",
  "classic brass carved desk lamp": "/product-images/CLASSIC BRASS CARVED DESK LAMP.png",
  "classic traditional 5 arm glass shade chandelier": "/product-images/CLASSIC TRADITIONAL 5-ARM GLASS SHADE CHANDELIER.png",
  "classic victorian gold branch chandelier": "/product-images/CLASSIC VICTORIAN GOLD BRANCH CHANDELIER.png",
  "clear glass bell flush hanging drop": "/product-images/CLEAR GLASS BELL FLUSH HANGING DROP.png",
  "cob led deep recessed downlight": "/product-images/COB LED DEEP RECESSED DOWNLIGHT.png",
  "compact matte charcoal outdoor cylinder": "/product-images/COMPACT MATTE CHARCOAL OUTDOOR CYLINDER.png",
  "concave arch gold lined decorative sconce": "/product-images/CONCAVE ARCH GOLD-LINED DECORATIVE SCONCE.png",
  "cone cap radial shield louver bollard": "/product-images/CONE CAP RADIAL SHIELD LOUVER BOLLARD.png",
  "contemporary black six arm spider chandelier": "/product-images/CONTEMPORARY BLACK SIX-ARM SPIDER CHANDELIER.png",
  "cp200cr double socket frame cr rose gold accent": "/product-images/CP200CR DOUBLE SOCKET FRAME CR (ROSE GOLD ACCENT).png",
  "cp200cr double socket frame cr rose gold accent 1": "/product-images/CP200CR DOUBLE SOCKET FRAME CR (ROSE GOLD ACCENT)_1.png",
  "cylindrical tuxedo minimalist single pendant": "/product-images/CYLINDRICAL TUXEDO MINIMALIST SINGLE PENDANT.png",
  "cylindrical updown covers compact matrix": "/product-images/CYLINDRICAL UPDOWN COVERS COMPACT MATRIX.png",
  "db box recessed wall enclosure": "/product-images/DB BOX RECESSED WALL ENCLOSURE.png",
  "delta pillar wedge exterior sconce": "/product-images/DELTA PILLAR WEDGE EXTERIOR SCONCE.png",
  "double layer crystal cakecut ring chandelier": "/product-images/DOUBLE LAYER CRYSTAL CAKECUT RING CHANDELIER.png",
  "double orbit spark fitting matrix": "/product-images/DOUBLE ORBIT SPARK FITTING MATRIX.png",
  "e324 universal wh ac switch gold": "/product-images/E324 UNIVERSAL (WH & AC) SWITCH GOLD.png",
  "eclipse ring glow black wall disc": "/product-images/ECLIPSE RING GLOW BLACK WALL DISC.png",
  "eco grille led surface round light": "/product-images/ECO GRILLE LED SURFACE ROUND LIGHT.png",
  "electrical distribution box openclosed view": "/product-images/ELECTRICAL DISTRIBUTION BOX (OPENCLOSED VIEW).png",
  "embedded crystal flush mount glow fixture": "/product-images/EMBEDDED CRYSTAL FLUSH-MOUNT GLOW FIXTURE.png",
  "exterior architectural brick fitting mix": "/product-images/EXTERIOR ARCHITECTURAL BRICK FITTING MIX.png",
  "flat hollow port slit footpath light": "/product-images/FLAT HOLLOW PORT SLIT FOOTPATH LIGHT.png",
  "flush mount metallic distribution enclosure": "/product-images/FLUSH MOUNT METALLIC DISTRIBUTION ENCLOSURE.png",
  "flush slimline retrofit downlight panel": "/product-images/FLUSH SLIMLINE RETROFIT DOWNLIGHT PANEL.png",
  "geometric triangle reinforced wooden cage pendant": "/product-images/GEOMETRIC TRIANGLE REINFORCED WOODEN CAGE PENDANT.png",
  "gi flush boxes multi pack": "/product-images/GI FLUSH BOXES MULTI-PACK.png",
  "gold flute crystal sconce isolated close up": "/product-images/GOLD FLUTE CRYSTAL SCONCE (ISOLATED CLOSE-UP).png",
  "gold flute spire luxury crystal fixture": "/product-images/GOLD FLUTE SPIRE LUXURY CRYSTAL FIXTURE.png",
  "grey reinforced commercial area bollards": "/product-images/GREY REINFORCED COMMERCIAL AREA BOLLARDS.png",
  "heavy duty extension cable reel": "/product-images/HEAVY DUTY EXTENSION CABLE REEL.png",
  "heavy duty industrial change over switch": "/product-images/HEAVY DUTY INDUSTRIAL CHANGE-OVER SWITCH.png",
  "hyundai square led driver driven panel": "/product-images/HYUNDAI SQUARE LED DRIVER DRIVEN PANEL.png",
  "intertwined matte black led loops": "/product-images/INTERTWINED MATTE BLACK LED LOOPS.png",
  "intertwined matte black led loops 1": "/product-images/INTERTWINED MATTE BLACK LED LOOPS_1.png",
  "intertwined matte black led loops 2": "/product-images/INTERTWINED MATTE BLACK LED LOOPS_2.png",
  "kans ans nymhy cable roll yellow": "/product-images/KANS   ANS NYMHY CABLE ROLL YELLOW.png",
  "kans energy bulb pink box": "/product-images/KANS ENERGY BULB (PINK BOX).png",
  "kans energy bulb 1030lm e27": "/product-images/KANS ENERGY BULB 1030lm E27.png",
  "kans energy bulb 1050lm b22": "/product-images/KANS ENERGY BULB 1050lm B22.png",
  "kans energy bulb 1250lm e27": "/product-images/KANS ENERGY BULB 1250lm E27.png",
  "kans energy bulb 210lm": "/product-images/KANS ENERGY BULB 210lm.png",
  "kans energy bulb 350lm": "/product-images/KANS ENERGY BULB 350lm.png",
  "kans energy bulb lamps b22": "/product-images/KANS ENERGY BULB LAMPS B22.png",
  "kans energy bulb lamps e27": "/product-images/KANS ENERGY BULB LAMPS E27.png",
  "kans energy bulb spiral type": "/product-images/KANS ENERGY BULB SPIRAL TYPE.png",
  "kans led 15w b22 wt t type": "/product-images/KANS LED 15W B22 WT (T-TYPE).png",
  "kans led 15w b22 wt t type 2": "/product-images/KANS LED 15W B22 WT (T-TYPE)_2.png",
  "kans led 15w e27": "/product-images/KANS LED 15W E27.png",
  "kans led 30w led indoor": "/product-images/KANS LED 30W (LED INDOOR).png",
  "kans led 30w b22 wt t type": "/product-images/KANS LED 30W B22 WT (T-TYPE).png",
  "kans led 40w b22 wt t type": "/product-images/KANS LED 40W B22 WT (T-TYPE).png",
  "kans led 50w b22 wt t type": "/product-images/KANS LED 50W B22 WT (T-TYPE).png",
  "kans led 9w b22 wt t type": "/product-images/KANS LED 9W B22 WT (T-TYPE).png",
  "kans led panel driver enclosure": "/product-images/KANS LED PANEL DRIVER ENCLOSURE.png",
  "king led orange box outdoor bulkhead copy 1": "/product-images/KING LED ORANGE BOX OUTDOOR BULKHEAD (copy 1).png",
  "king led orange box outdoor bulkhead": "/product-images/KING LED ORANGE BOX OUTDOOR BULKHEAD.png",
  "led panel light office surface pair": "/product-images/LED PANEL LIGHT OFFICE SURFACE PAIR.png",
  "led street lamp box": "/product-images/LED STREET LAMP BOX.png",
  "led wl 7w 3000k": "/product-images/LED WL 7W (3000K).png",
  "luxury stained fabric table shade set": "/product-images/LUXURY STAINED FABRIC TABLE SHADE SET.png",
  "magnetic contactor fitting": "/product-images/MAGNETIC CONTACTOR FITTING.png",
  "main switchboard interior panel": "/product-images/MAIN SWITCHBOARD INTERIOR PANEL.png",
  "matte black finned street pillar bollards": "/product-images/MATTE BLACK FINNED STREET PILLAR BOLLARDS.png",
  "mini cylindrical spotlight updown stem assembly": "/product-images/MINI CYLINDRICAL SPOTLIGHT UPDOWN STEM ASSEMBLY.png",
  "mini led adjustable spotlight series": "/product-images/MINI LED ADJUSTABLE SPOTLIGHT SERIES.png",
  "minimalist wireless doorbell chime set": "/product-images/MINIMALIST WIRELESS DOORBELL & CHIME SET.png",
  "modern horizontal gold rings pendant": "/product-images/MODERN HORIZONTAL GOLD RINGS PENDANT.png",
  "modular distribution enclosures row": "/product-images/MODULAR DISTRIBUTION ENCLOSURES ROW.png",
  "modular fuse switch disconnector bank": "/product-images/MODULAR FUSE SWITCH DISCONNECTOR BANK.png",
  "multi tier step louver brick wall cove": "/product-images/MULTI-TIER STEP LOUVER BRICK WALL COVE.png",
  "nordic gold lined dome pendant lamp": "/product-images/NORDIC GOLD-LINED DOME PENDANT LAMP.png",
  "nordic loop hoop gold pendant": "/product-images/NORDIC LOOP HOOP GOLD PENDANT.png",
  "optic mist surface mount ceiling round": "/product-images/OPTIC MIST SURFACE MOUNT CEILING ROUND.png",
  "orient ceiling rose fan dimmer": "/product-images/ORIENT CEILING ROSE FAN DIMMER.png",
  "oval gold band hoop pendant unit": "/product-images/OVAL GOLD BAND HOOP PENDANT UNIT.png",
  "oval mesh inner crystal teardrop pendant": "/product-images/OVAL MESH INNER CRYSTAL TEARDROP PENDANT.png",
  "oval nautical bulkhead guard assembly": "/product-images/OVAL NAUTICAL BULKHEAD GUARD ASSEMBLY.png",
  "p301f 1 gang 1 way switch f302f": "/product-images/P301F 1 GANG 1 WAY SWITCH (F302F).png",
  "p408m 13a double multi socket": "/product-images/P408M 13A DOUBLE MULTI SOCKET.png",
  "p408mb 13a double multi socket 2 usb": "/product-images/P408MB 13A DOUBLE MULTI SOCKET + 2 USB.png",
  "pagoda step roof charcoal cage lantern": "/product-images/PAGODA STEP ROOF CHARCOAL CAGE LANTERN.png",
  "paisley teardrop frame seed amber glass sconce": "/product-images/PAISLEY TEARDROP FRAME SEED AMBER GLASS SCONCE.png",
  "palatial empire crystal drift chandelier": "/product-images/PALATIAL EMPIRE CRYSTAL DRIFT CHANDELIER.png",
  "pluto led ceiling mix series box": "/product-images/PLUTO LED CEILING MIX SERIES BOX.png",
  "pop up floor socket box pack": "/product-images/POP-UP FLOOR SOCKET BOX PACK.png",
  "premium layered crystal chandelier selection": "/product-images/PREMIUM LAYERED CRYSTAL CHANDELIER SELECTION.png",
  "premium smd floodlight 200w yellow handle copy 1": "/product-images/PREMIUM SMD FLOODLIGHT 200W (YELLOW HANDLE) (copy 1).png",
  "premium smd floodlight 200w yellow handle": "/product-images/PREMIUM SMD FLOODLIGHT 200W (YELLOW HANDLE).png",
  "pure copper earth tape strip roll": "/product-images/PURE COPPER EARTH TAPE STRIP ROLL.png",
  "recessed casing linear foot path light": "/product-images/RECESSED CASING LINEAR FOOT PATH LIGHT.png",
  "recessed cylindrical spotlight matrix": "/product-images/RECESSED CYLINDRICAL SPOTLIGHT MATRIX.png",
  "recessed oval": "/product-images/RECESSED OVAL.png",
  "rectangular amber glass cove wall light copy 1": "/product-images/RECTANGULAR AMBER GLASS COVE WALL LIGHT (copy 1).png",
  "rectangular amber glass cove wall light": "/product-images/RECTANGULAR AMBER GLASS COVE WALL LIGHT.png",
  "rectangular compact smooth exterior updown fitting": "/product-images/RECTANGULAR COMPACT SMOOTH EXTERIOR UPDOWN FITTING.png",
  "rectangular shield path way drop deflector": "/product-images/RECTANGULAR SHIELD PATH WAY DROP DEFLECTOR.png",
  "rib glass industrial pipeline block bulkhead": "/product-images/RIB-GLASS INDUSTRIAL PIPELINE BLOCK BULKHEAD.png",
  "round back split passage block light": "/product-images/ROUND BACK SPLIT PASSAGE BLOCK LIGHT.png",
  "round globe garden bollard": "/product-images/ROUND GLOBE GARDEN BOLLARD.png",
  "round recessed mini panel dual pack": "/product-images/ROUND RECESSED MINI PANEL DUAL PACK.png",
  "round surface led bulkhead black rim": "/product-images/ROUND SURFACE LED BULKHEAD BLACK RIM.png",
  "rounded edge linear corridor bulkhead": "/product-images/ROUNDED EDGE LINEAR CORRIDOR BULKHEAD.png",
  "semi circular louver matte outdoor cove": "/product-images/SEMI-CIRCULAR LOUVER MATTE OUTDOOR COVE.png",
  "single core pvc wire coil grey": "/product-images/SINGLE CORE PVC WIRE COIL GREY.png",
  "slim panel led fixture set": "/product-images/SLIM PANEL LED FIXTURE SET.png",
  "slimline embedded matrix square led": "/product-images/SLIMLINE EMBEDDED MATRIX SQUARE LED.png",
  "slimround led panel light flat type": "/product-images/SLIMROUND LED PANEL LIGHT FLAT TYPE.png",
  "slit cove vertical architectural outdoor mount": "/product-images/SLIT COVE VERTICAL ARCHITECTURAL OUTDOOR MOUNT.png",
  "slit glow architectural horizontal light block": "/product-images/SLIT GLOW ARCHITECTURAL HORIZONTAL LIGHT BLOCK.png",
  "smoked glass orb triple head mix": "/product-images/SMOKED GLASS ORB TRIPLE HEAD MIX.png",
  "smooth recessed flood cove bulkhead": "/product-images/SMOOTH RECESSED FLOOD COVE BULKHEAD.png",
  "solar floodlight kit with panel 100w": "/product-images/SOLAR FLOODLIGHT KIT WITH PANEL 100W.png",
  "spherical burst crystal chandelier": "/product-images/SPHERICAL BURST CRYSTAL CHANDELIER.png",
  "spiral crystal waterdrop pendant system": "/product-images/SPIRAL CRYSTAL WATERDROP PENDANT SYSTEM.png",
  "square crystal enclosed ceiling fixture": "/product-images/SQUARE CRYSTAL ENCLOSED CEILING FIXTURE.png",
  "square face dual glow column sconce": "/product-images/SQUARE FACE DUAL GLOW COLUMN SCONCE.png",
  "square gimbal downlight with driver": "/product-images/SQUARE GIMBAL DOWNLIGHT WITH DRIVER.png",
  "st231d led ventilation wall grille": "/product-images/ST231D LED VENTILATION WALL GRILLE.jpg",
  "st3174 24w led grill fitting copy 1": "/product-images/ST3174 24W LED GRILL FITTING (copy 1).png",
  "st3174 24w led grill fitting": "/product-images/ST3174 24W LED GRILL FITTING.png",
  "stadium track oval matte black bulkhead": "/product-images/STADIUM TRACK OVAL MATTE BLACK BULKHEAD.png",
  "stainless steel updown pipeline light column": "/product-images/STAINLESS STEEL UPDOWN PIPELINE LIGHT COLUMN.png",
  "starburst five head gold chandelier cluster": "/product-images/STARBURST FIVE-HEAD GOLD CHANDELIER CLUSTER.png",
  "starburst flush ceiling decor unit": "/product-images/STARBURST FLUSH CEILING DECOR UNIT.png",
  "starburst three bead drop cove light": "/product-images/STARBURST THREE-BEAD DROP COVE LIGHT.jpeg",
  "stemware glass type gold luxury wall fitting": "/product-images/STEMWARE GLASS TYPE GOLD LUXURY WALL FITTING.jpeg",
  "street stainless cylinder flush top covers": "/product-images/STREET STAINLESS CYLINDER FLUSH TOP COVERS.png",
  "surge protective device spd": "/product-images/SURGE PROTECTIVE DEVICE (SPD).png",
  "swan neck hollow icicle crystal sconce": "/product-images/SWAN NECK HOLLOW ICICLE CRYSTAL SCONCE.png",
  "t304ab 2 gang 2 way switch gold wt": "/product-images/T304AB 2 GANG 2 WAY SWITCH GOLD + WT.png",
  "t306ab 3 gang 2 way switch gold wt": "/product-images/T306AB 3 GANG 2 WAY SWITCH GOLD + WT.png",
  "t306ab 3 gang 2 way switch gold wt 2": "/product-images/T306AB 3 GANG 2 WAY SWITCH GOLD + WT_2.png",
  "tinko bulb": "/product-images/TINKO BULB.png",
  "tinko led double pack panel fixture copy 1": "/product-images/TINKO LED DOUBLE PACK PANEL FIXTURE (copy 1).png",
  "tinko led double pack panel fixture": "/product-images/TINKO LED DOUBLE PACK PANEL FIXTURE.png",
  "tinko recessed square lighting fixture": "/product-images/TINKO RECESSED SQUARE LIGHTING FIXTURE.png",
  "tinko t series square suspended panel": "/product-images/TINKO T-SERIES SQUARE SUSPENDED PANEL.png",
  "traditional hip roof hood pillar light": "/product-images/TRADITIONAL HIP-ROOF HOOD PILLAR LIGHT.png",
  "triangular hood pathway fitting white": "/product-images/TRIANGULAR HOOD PATHWAY FITTING WHITE.png",
  "trio oval industrial cage bunker pack": "/product-images/TRIO OVAL INDUSTRIAL CAGE BUNKER PACK.png",
  "triple cone compact gold crystal set": "/product-images/TRIPLE CONE COMPACT GOLD CRYSTAL SET.png",
  "triple hoop ornate gold drop fixture": "/product-images/TRIPLE HOOP ORNATE GOLD DROP FIXTURE.png",
  "twin and earth cable coil white": "/product-images/TWIN AND EARTH CABLE COIL WHITE.png",
  "vintage glass tube round frame bollard": "/product-images/VINTAGE GLASS TUBE ROUND FRAME BOLLARD.png",
  "vintage hoop frame pillar lantern": "/product-images/VINTAGE HOOP FRAME PILLAR LANTERN.png",
  "vp167j tv socket satelite gold vc101j": "/product-images/VP167J TV SOCKET + SATELITE GOLD (VC101J).png",
  "vp302y 1 gang 2 way switch silver": "/product-images/VP302Y 1 GANG 2 WAY SWITCH SILVER.png",
  "vp306j 3 gang 2 way switch gold vc103j": "/product-images/VP306J 3 GANG 2 WAY SWITCH GOLD (VC103J).png",
  "vp306y 3 gang 2 way switch silver vc 320t": "/product-images/VP306Y 3 GANG 2 WAY SWITCH SILVER (VC-320T).png",
  "vp306y 3 gang 2 way switch silver vc105j": "/product-images/VP306Y 3 GANG 2 WAY SWITCH SILVER (VC105J).png",
  "vp324j ac air condition switch gold": "/product-images/VP324J-AC AIR CONDITION SWITCH GOLD.png",
  "vp324j wh water heater switch gold": "/product-images/VP324J-WH WATER HEATER SWITCH GOLD.png",
  "vp324y ac air condition switch silver": "/product-images/VP324Y-AC AIR CONDITION SWITCH SILVER.png",
  "vp352y dimmer switch silver vp 130 3": "/product-images/VP352Y DIMMER SWITCH SILVER (VP 130-3).png",
  "vp407j single socket gold vc 401j": "/product-images/VP407J SINGLE SOCKET GOLD (VC-401J).png",
  "vp407y single socket silver vc 401y": "/product-images/VP407Y SINGLE SOCKET SILVER (VC-401Y).png",
  "vp408j 13a double socket gold": "/product-images/VP408J 13A DOUBLE SOCKET GOLD.png",
  "vp408mbj 13a double multi socket gold with usb vc500": "/product-images/VP408MBJ 13A DOUBLE MULTI SOCKET GOLD WITH USB (VC500).png",
  "vp408y 13a double socket brushed metal": "/product-images/VP408Y 13A DOUBLE SOCKET BRUSHED METAL.png",
  "vp408y 13a double socket silver": "/product-images/VP408Y 13A DOUBLE SOCKET SILVER.png",
  "vp408y 13a double socket stainless steel": "/product-images/VP408Y 13A DOUBLE SOCKET STAINLESS STEEL.png",
  "vp432j tv socket gold": "/product-images/VP432J TV SOCKET GOLD.png",
  "vp432y tv socket silver": "/product-images/VP432Y TV SOCKET SILVER.png",
  "vp432y tv socket stainless steel": "/product-images/VP432Y TV SOCKET STAINLESS STEEL.png",
  "w509 13a single multi socket adaptor usb": "/product-images/W509 13A SINGLE MULTI SOCKET ADAPTOR+ USB.png",
  "wave curved edge compact step fitting": "/product-images/WAVE CURVED EDGE COMPACT STEP FITTING.png",
  "wavy reinforced surface cable tray": "/product-images/WAVY REINFORCED SURFACE CABLE TRAY.png",
  "x frame geometric backlight disk": "/product-images/X-FRAME GEOMETRIC BACKLIGHT DISK.png"
};

export function normalizeProductKey(name: string): string {
  return name
    .toLowerCase()
    .replace(/\.(png|jpg|jpeg|webp|gif|svg)$/i, '')
    .replace(/[^a-z0-9]+/g, ' ')
    .trim()
    .replace(/\s+/g, ' ');
}

export function resolveImageUrl(url: string | null | undefined): string {
  if (!url) return '';
  // Already a local path
  if (url.startsWith('/product-images/')) return '/images/products/' + url.substring('/product-images/'.length);
  // Legacy Supabase URL fallback
  const prefix = 'https://njgdeljfvprnkckgyiuy.supabase.co/storage/v1/object/public/COFKANSELECTRICALS/Products/';
  if (url.startsWith(prefix)) {
    return '/images/products/' + decodeURIComponent(url.substring(prefix.length));
  }
  return url;
}

export function lookupProductImage(name: string | undefined | null): string | null {
  if (!name) return null;
  const url = PRODUCT_IMAGE_URLS[normalizeProductKey(name)] ?? null;
  return url ? resolveImageUrl(url) : null;
}
